# Generated by Django 5.1.4 on 2024-12-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lists',
            old_name='task',
            new_name='tasks',
        ),
    ]
